version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: goflydb
      MYSQL_USER: goflyuser
      MYSQL_PASSWORD: goflypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  gofly:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: gofly_container
    ports:
      - "8081:8081"
    environment:
      DB_HOST: 8.138.99.112
      DB_USER: go-fly
      DB_PASSWORD: 8Ck6m3Kc4jrSdjFp
      DB_NAME: go-fly
      DB_PORT: 3306

volumes:
  mysql_data:
    driver: local 